services:
  web:
    build: .
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      RAILS_LOG_TO_STDOUT: enabled
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: minesweeper_development
      MYSQL_USER: minesweeper
      MYSQL_PASSWORD: minesweeper
      MYSQL_ROOT_PASSWORD: minesweeper
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
